### ISSUE TITLE
What is my Error?

### ISSUE THREAD

**Issue by EmadDeve20** [ArthurBacci64/Teditor#17]
Hello everyone I have an error in the making!
what is my Wrong?
![Screenshot 2021-02-21 05:06:34](https://user-images.githubusercontent.com/60766355/108613014-e70bd100-7402-11eb-80eb-5db2953ea299.png)

**Comment by arthurbacci** [comment]
This is not an error, just a warning. You can ignore it and continue. \:D

**Comment by arthurbacci** [comment]
Does `./ted` works? Before making again, you will need to run `make clean`.

This does not works:
```
make
make
```
But this works:
```
make
make clean
make
```

**Comment by EmadDeve20** [comment]
yea it's working. Thanks 👍🏻

**Comment by arthurbacci** [comment]
No problems.
