### ISSUE TITLE
Proposed changes to config dialog

### ISSUE THREAD

**Issue by bynect** [ArthurBacci64/Teditor#25]
Hello, I was experimenting a little bit with config dialogs and I made the following major changes:

* Split into substrings the command and pass them as argument of the respective function. (This eliminates the need for multiple call to prompt)
* Add hints when writing commands in config dialogs (still at an early stage, but functioning). (This was made as a substitution for prompts custom messages)
* Return a bool from `detect_extension` which indicates if a syntax was found or not

You can see all the changes in this branch: https://github.com/bynect/Teditor/tree/major.
Since this are somewhat bigger changes than the others, I was hoping to hear your opinions before creating a pr.

**Comment by arthurbacci** [comment]
Looks good, I will test it.

**Comment by arthurbacci** [comment]
PR :?
