### ISSUE TITLE
.editorconfig support

### ISSUE THREAD

**Issue by arthurbacci** [ArthurBacci64/Teditor#27]
Add a configuration file interpreter for basic configuration.

**Comment by bynect** [comment]
I have implemented a very rudimentary config file parser, could you please tell me what do you think about it? Should I do pr for  this?
Branch: https://github.com/bynect/Teditor/tree/config2

**Comment by arthurbacci** [comment]
I was thinking about a .ini like syntax. Something like this:

```
[c]
autotab 1
use-spaces 0
tablen 4

[py]
autotab 1
use-spaces 1
tablen 2
```

**Comment by arthurbacci** [comment]
I will implement it ;)

**Comment by bynect** [comment]
> I will implement it ;)

What do you think about supporting an universal configuration file like [editorconfig](https://editorconfig.org/)? (Not necessarily the only one)

**Comment by arthurbacci** [comment]
> > I will implement it ;)
> 
> What do you think about supporting an universal configuration file like [editorconfig](https://editorconfig.org/)? (Not necessarily the only one)

I think it is a good idea.

**Comment by arthurbacci** [comment]
Editorconfig support seems to be working on #66. @bynect
