### ISSUE TITLE
Add a way to highlight number literals

### ISSUE THREAD

**Issue by bynect** [ArthurBacci64/Teditor#34]
For example: `0xa0` or `1234`

**Comment by arthurbacci** [comment]
` ([0-9xb]+)` is something that can match it in C/C++

**Comment by bynect** [comment]
> ` ([0-9xb]+)` is something that can match it in C/C++

Can it be implemented without using regex?

**Comment by arthurbacci** [comment]
Of course, I send that regex just for example of how to match it.

**Comment by bynect** [comment]
Ok. For now I am trying to implement an auto-indent option for brackets/blocks (a sort of super autotab), so I will look into this later. 

Also I think is super cool the idea to create a configuration file (suggestion: initially as INI since its relatively easy to parse) to store configs from one session to another.

**Comment by bynect** [comment]
Closing for #39
