### ISSUE TITLE
Modify the way ted can be closed

### ISSUE THREAD

**Issue by bynect** [ArthurBacci64/Teditor#38]
Actually ted can be closed just with ctrl+c, even if unsaved changes to a file have been made.

Isn't a little bit too easy to erroneously quit in this way? Should ted prompt the user for a confirm message (ex: Are you sure to quit?)? Or maybe introduce the exit/quit config dialog (like vim)?

**Comment by bynect** [comment]
Maybe we should add a `dirty` boolean flag that is set when the file is modified, and if the user presses ctrl+c and this flag is set ted will prompt for confirmation like `Exit without saving` (true/false)

**Comment by arthurbacci** [comment]
I am doing this now.

**Comment by arthurbacci** [comment]
#46 closes
