### ISSUE TITLE
Carriage return (0x0D) removes line numbers

### ISSUE THREAD

**Issue by Br0000k** [ArthurBacci64/Teditor#4]
When there is a carriage return character (0x0D), it removes the line number of the line it's on. I think CR (carriage return) needs to be interpreted as a new line (0x0a, '\n', line feed).

**Comment by arthurbacci** [comment]
Thanks for making the issue. I will try to fix it just now.

**Comment by arthurbacci** [comment]
I closed for accident lol, sorry

**Comment by arthurbacci** [comment]
Does the last commit solved it?

**Comment by Br0000k** [comment]
Unfortunately, it doesn't. Still the same. Thank you for accepting my pull request btw! :)

**Comment by arthurbacci** [comment]
I will try to figure out the exactly why of this is hapenning. Thanks for making it public.

**Comment by Br0000k** [comment]
No problem. Happy to help :)

**Comment by arthurbacci** [comment]
Can you say exactly how and why are you sending a carriage return to the code, please?

**Comment by arthurbacci** [comment]
> Unfortunately, it doesn't. Still the same. Thank you for accepting my pull request btw! :)

Did you do `make clean` before `make`?

**Comment by arthurbacci** [comment]
Ok, now I undertand the issue, I thought it was related to typing a carriage return, it is when opening a file that has carriage returns.
I opened a CRLF file and everything were buggy.
Now that I undertand, I will try to fix it.

**Comment by arthurbacci** [comment]
Solved: https://github.com/ArthurBacci64/Teditor/commit/20f0b35ce4abfaa8d5f13b7917f3eddae845090e.

**Comment by Br0000k** [comment]
It works better but it removes the first character after the carriage return. Btw I see you have changed your license to GPL. I'm fine with this [but you shouldn't relicense after someone has contributed](https://opensource.guide/legal/). I contributed to README.md but I agree to the license change. I'm unsure if public domain is even irrevocable.

**Comment by arthurbacci** [comment]
Sorry for not warning you

**Comment by arthurbacci** [comment]
I added suport for LF and CRLF, looks like you are trying a file thats only CR, I will try implementing it

**Comment by arthurbacci** [comment]
Looks like the default of Linux is LF, the default of Windows is CRLF and the default of Mac is CR.

**Comment by arthurbacci** [comment]
The CR can not just be interpreted as LF, otherwise, Windows files would have all line breaks replaced for two lines breaks. This project does not aims Windows support, but sometimes opening Windows files in Linux/BSD/MacOS is needed.

**Comment by arthurbacci** [comment]
Added support for opening this type of file :D, support for saving in the same format not done yet

**Comment by Br0000k** [comment]
> Sorry for not warning you

That's fine! Like I said, I'm fine with the license change. It really doesn't matter to me. But the issue around relicensing is something worth knowing about.

> The CR can not just be interpreted as LF, otherwise, Windows files would have all line breaks replaced for two lines breaks.

I made a mistake then :) Thank you for following me btw! And for adding CR(LF) support.

**Comment by arthurbacci** [comment]
Ok, now I am making the part of saving, because it is now saving all files as LF, after fixing it, I will commit

**Comment by arthurbacci** [comment]
Done

**Comment by Br0000k** [comment]
> Can you say exactly how and why are you sending a carriage return to the code, please?

cat /dev/random :) best testing tool ever.. btw I think there are other characters that seem to disrupt the line numbers and the arrow keys seem a bit buggy as well.

**Comment by arthurbacci** [comment]
This editor will not work well with random sequences, it is made to be a text editor, not a binary text one.

**Comment by arthurbacci** [comment]
Maybe one day I will create `tedbin`, but not now.

**Comment by arthurbacci** [comment]
I searched a bit more, and looks like the most commons line break types are LF and CRLF. And MacOS uses LF (like Linux does), only the old versions of MacOS (the classical MacOS) uses CR.
