### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by bynect** [ArthurBacci64/Teditor#47]
![xxx](https://user-images.githubusercontent.com/68197565/113102642-96a44200-91fe-11eb-98cf-72ce515d0181.jpg)
I am not sure if this is a problem with the syntax highlighter or something else

**Comment by bynect** [comment]
This bug was introduced in commit 8514eeb9e5a22fcceb88bd695aab1a08d2a50d8f

**Comment by bynect** [comment]
Why did you comment out this line?
```
        // syntaxHighlight();
```

**Comment by arthurbacci** [comment]
> Why did you comment out this line?
> 
> ```
>         // syntaxHighlight();
> ```

Probably, I thought it was not necessary.

**Comment by arthurbacci** [comment]
#48 closes
