### ISSUE TITLE
Error message when there's a pipe

### ISSUE THREAD

**Issue by trqt** [ArthurBacci64/Teditor#62]
`$ echo string | ./ted` 
![2021-08-01T15:29:51,151068207-03:00](https://user-images.githubusercontent.com/30443527/127781622-b7587e0c-b47c-4bbb-812f-3d40c95848c6.png)

**Comment by arthurbacci** [comment]
What's wrong? I never said that it works with pipes

**Comment by arthurbacci** [comment]
What should be done in this case? `echo string | ted` should be the same as `echo string > ~/.config/ted/buffer` and `echo string | ted file.txt` the same as `echo string > file.txt`? But and `echo string | ted file1.txt file2.txt`? The same as `echo a | tee file1.txt > file2.txt`?
Or should it just print an error message and die?
Or should it try to remove all files in `/`?

**Comment by arthurbacci** [comment]
![sussy](https://user-images.githubusercontent.com/59983362/127786585-0d8043f2-f254-49e5-beab-2287b23a24d9.png)
Fixed?

**Comment by ArthurBacci64** [comment]
It does not cra

**Comment by trqt** [comment]
> What should be done in this case? `echo string | ted` should be the same as `echo string > ~/.config/ted/buffer` and `echo string | ted file.txt` the same as `echo string > file.txt`? But and `echo string | ted file1.txt file2.txt`? The same as `echo a | tee file1.txt > file2.txt`?
> Or should it just print an error message and die?
> Or should it try to remove all files in `/`?

It should paste the stdin in the file and start editing it, it already does that, but it hangs in the process

**Comment by arthurbacci** [comment]
> > What should be done in this case? `echo string | ted` should be the same as `echo string > ~/.config/ted/buffer` and `echo string | ted file.txt` the same as `echo string > file.txt`? But and `echo string | ted file1.txt file2.txt`? The same as `echo a | tee file1.txt > file2.txt`?
> > Or should it just print an error message and die?
> > Or should it try to remove all files in `/`?
> 
> It should paste the stdin in the file and start editing it, it already does that, but it hangs in the process

You mean just appending to the file?

**Comment by trqt** [comment]
After three years I changed my position, it's better to just ignore it

**Comment by arthurbacci** [comment]
Ok
